---
name: build
on:
  - push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile with gcc
        run: find . -type f -name '*.c' -exec gcc -Wall -Werror -c -std=c11 {} +
