---
name: build
on:
  - push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get install -y --no-install-recommends clang-format
      - name: clang-format
        run: find . -type f -name '*.c' -exec clang-format {} +
